services:
  - type: web
    name: bookmyseat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookmyseat.wsgi:application
    autoDeploy: true
    region: oregon
