services:
  - type: web
    name: django-movie-booking
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bookmyseat.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
    autoDeploy: true
